### ISSUE TITLE
please release a new version of this crate

### ISSUE THREAD

**Issue by davide125** [rbspy/rbspy-testdata#6]
Currently rbspy has `rbspy-testdata = { git = "https://github.com/rbspy/rbspy-testdata", branch = "master" }` in its Cargo.toml, which makes packaging tricky, as the latest published version of `rbspy-testdata` doesn't contain all necessary changes for it to compile. Consider cutting a new release and uploading it to crates, then updating the dependency in `rbspy` to something like
`rbspy-testdata = { version = "0.1.3" }` to make things easier down the road.

**Comment by acj** [comment]
@davide125 We can do a new release. I'm curious how this repo affects packaging, though, since rbspy's Cargo.lock includes the respective commit from rbspy-testdata master that's needed for a reproducible build. Does every dependency need to be packaged separately for your distro?

@jvns, it looks like you're the sole owner of the rbspy-testdata and rbspy-ruby-structs crates. Could you add me to those, please?

**Comment by davide125** [comment]
Thanks! Fedora packages every crate separately, and every crate has only one version within the entire distribution (with the exception of temporary compat packages to ease rebuilds). `Cargo.toml` is parsed to figure out dependencies (and patched if needed), and to my understanding `Cargo.lock` is ignored.

**Comment by jvns** [comment]
Oops, I invited you as an owner! I also added @rbspy/owners as an owner of those crates

**Comment by acj** [comment]
Thanks!

I tagged version 0.1.4, but we've exceeded the maximum crate size (10MB) for crates.io, so the crate hasn't been updated yet. I emailed them to ask for an increase.

**Comment by acj** [comment]
The crate size limit is now 50MB. 0.1.4 is published.
